### ISSUE TITLE
gRPC Extension Roadmap

### ISSUE THREAD

**Issue by rotemtam** [ent/ent#2446]
This issue tracks progress on the [gRPC Extension](https://entgo.io/docs/grpc-intro/) for Ent.

- [x] Protobuf Definition Generation
- [x] gRPC Service Definition Generation
- [x] Create 
- [x] Update
- [x] Delete
- [ ] JSON Support [Discussion](https://github.com/ent/ent/discussions/1690)
- [x] List
  - [X] Keyset Pagination
  - [ ] Pagination on non-id fields
  - [ ] Query Predicates
- [ ] Batch Operations
  - [ ]  BatchCreate support [AIP-233](https://google.aip.dev/233)
  - [ ]  BatchUpdate support [AIP-234](https://google.aip.dev/234)
  - [ ]  BatchDelete support [AIP-235](https://google.aip.dev/235)

**Comment by philhug** [comment]
BatchGet AIP-231 would be helpful to reduce roundtrips:
https://google.aip.dev/231

**Comment by rotemtam** [comment]
> BatchGet AIP-231 would be helpful to reduce roundtrips:
> 
> https://google.aip.dev/231
> 
> 

@philhug ping me on the Ent discord channel? I'd like to hear more about your use case
